name: Build lede

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      cache_toolchain:
        description: '启用Cache缓存Toolchain'
        required: false
        default: 'true'
      single_model:
        description: '启用单线程编译'
        required: false
        default: 'false'
      use_custom_files:
        description: '使用自定义files'
        required: false
        default: 'false'
      upload_action:
        description: '上传固件到Action'
        required: false
        default: 'false'
      upload_release:
        description: '上传固件到Release'
        required: false
        default: 'true'
      upload_packages:
        description: '上传Packages到Action'
        required: false
        default: 'false'
      repo_url:
        description: '使用的OpenWrt源码地址'
        required: false
        default: 'https://github.com/coolsnowwolf/lede'
      commit_id:
        description: '使用源码特定Commit ID'
        required: false
        default: ''
        
env:
  REPO_URL: ${{ inputs.repo_url || 'https://github.com/coolsnowwolf/lede' }}
  REPO_BRANCH: master
  FEEDS_CONF: feeds.conf.default
  CONFIG_FILE: .config
  DIY_FEED_SH: diy-feed.sh
  DIY_PACKAGE_SH: diy-package.sh
  TZ: Asia/Shanghai
  COMMIT_ID: ${{ inputs.commit_id || '' }}
  FILE_NAME: 3865U

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write

    steps:
    - name: "Optimize Disk Space"
      uses: "hugoalh/disk-space-optimizer-ghaction@v0.8.1"
      with:
        operate_sudo: "True"
        general_include: ".+"
        general_exclude: |-
          ^GCC$
          ^G\+\+$
          Clang
          LLVM
        docker_include: ".+"
        docker_prune: "True"
        docker_clean: "True"
        apt_prune: "True"
        apt_clean: "True"
        homebrew_prune: "True"
        homebrew_clean: "True"
        npm_prune: "True"
        npm_clean: "True"
        os_swap: "True"

    - name: "Initialization Environment"
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo bash -c 'bash <(curl -s https://build-scripts.immortalwrt.org/init_build_environment.sh)'
        # sudo apt autoremove
        # sudo apt autoclean
        # sudo apt-get clean
        # sudo -E apt-get -qq update
        # sudo -E apt-get -qq install ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential bzip2 ccache cmake cpio curl device-tree-compiler flex gawk gcc-multilib g++-multilib gettext genisoimage git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libfuse-dev libglib2.0-dev  libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libpython3-dev libreadline-dev libssl-dev libtool lrzsz msmtp ninja-build p7zip p7zip-full patch pkgconf python3 python3-pyelftools python3-setuptools qemu-utils rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev clang-19 llvm-19 dwarves
        # sudo -E apt-get -qq autoremove --purge
        # sudo -E apt-get -qq clean
        # sudo rm -rf /etc/apt/sources.list.d/* /usr/local/lib/android /opt/ghc /usr/share/dotnet /usr/local/graalvm /usr/local/.ghcup \
        # /usr/local/share/powershell /usr/local/share/chromium /usr/local/lib/node_modules
        sudo timedatectl set-timezone "$TZ"
        sudo chown $USER:$GROUPS $GITHUB_WORKSPACE
 
    - name: "Checkout"
      uses: actions/checkout@main
      with:
        ref: ${{ env.FILE_NAME }}
      
    - name: "Clone Source Code"
      working-directory: ./
      run: |
        df -hT $PWD
        git clone $REPO_URL -b $REPO_BRANCH openwrt
        if [ -n "$COMMIT_ID" ]; then
          cd openwrt
          git checkout $COMMIT_ID
        fi
        
    - name: "Get Cache Infos"
      run: |
        SOURCE_REPO="$(echo $REPO_URL | awk -F '/' '{print $(NF)}')"
        echo "SOURCE_REPO=$SOURCE_REPO" >> $GITHUB_ENV
        DEVICE_TARGET=$([ -e $CONFIG_FILE ] && cat $CONFIG_FILE | grep CONFIG_TARGET_BOARD | awk -F '"' '{print $2}' || echo "x86")
        echo "DEVICE_TARGET=$DEVICE_TARGET" >> $GITHUB_ENV
        DEVICE_SUBTARGET=$([ -e $CONFIG_FILE ] && cat $CONFIG_FILE | grep CONFIG_TARGET_SUBTARGET | awk -F '"' '{print $2}' || echo "64")
        echo "DEVICE_SUBTARGET=$DEVICE_SUBTARGET" >> $GITHUB_ENV
        
    - name: "Cache Toolchain"
      if: github.event.inputs.cache_toolchain == 'true'
      uses: HiGarfield/cachewrtbuild@main
      with:
        ccache: false
        mixkey: ${{ env.SOURCE_REPO }}-${{ env.REPO_BRANCH }}-${{ env.DEVICE_TARGET }}-${{ env.DEVICE_SUBTARGET }}
        prefix: 'openwrt'
   
    - name: "Use Custom Files"
      if: github.event.inputs.use_custom_files == 'true'
      env:
        REMOTE_HOST: ${{ secrets.SSH_HOST }}
        REMOTE_PASS: ${{ secrets.SSH_PASSWORD }}
        REMOTE_PORT: ${{ secrets.SSH_PORT || '22' }}
        REMOTE_USER: ${{ secrets.SSH_USERNAME || 'root' }}
      run: |
        mkdir -p ~/.ssh && chmod 700 ~/.ssh
        touch ~/.ssh/config && chmod 600 ~/.ssh/config
        echo "StrictHostKeyChecking no" >> ~/.ssh/config
        echo "UserKnownHostsFile /dev/null" >> ~/.ssh/config 
        chmod +x sync.sh
        if ! timeout 30m bash sync.sh; then
          echo "⚠️ sync.sh 执行失败"
        fi
        [ -e files ] && mv files openwrt/files
        # sudo chown -R root:root openwrt/files
     
    - name: "Load Custom Feed"
      run: |
        [ -e $FEEDS_CONF ] && mv $FEEDS_CONF openwrt/feeds.conf.default
        chmod +x $DIY_FEED_SH
        chmod +x $DIY_PACKAGE_SH
        cd openwrt
        $GITHUB_WORKSPACE/$DIY_FEED_SH
        ./scripts/feeds update -a
        $GITHUB_WORKSPACE/$DIY_PACKAGE_SH
        ./scripts/feeds install -a
        
    - name: "Download Package"
      run: |
        cd openwrt
        make defconfig
        make download -j8
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;

    - name: "Compile the Firmware"
      id: compile
      env:
        LOG_MODE: ${{ github.event.inputs.single_model }}
      run: |
        set -e
        rm -f openwrt/.config*
        [ -e $CONFIG_FILE ] && mv $CONFIG_FILE openwrt/.config
        cd openwrt
        # echo "" | make oldconfig > /dev/null 2>&1
        # 根据 log_model 输入值选择编译命令
        if [ "${{ github.event.inputs.single_model }}" = 'true' ]; then
          echo "Using verbose debug mode"
          make -j1 V=s
        else
          echo "Using $(nproc) thread compile"
          make -j$(nproc) || make -j1 V=s
        fi
        echo "status=success" >> $GITHUB_OUTPUT
        grep '^CONFIG_TARGET.*DEVICE.*=y' .config | sed -r 's/.*DEVICE_(.*)=y/\1/' > DEVICE_NAME
        [ -s DEVICE_NAME ] && echo "DEVICE_NAME=_$(cat DEVICE_NAME)" >> $GITHUB_ENV
        echo "FILE_DATE=_$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV

    - name: "Sent Message to Telegram"
      env:
        TELE_CHATID: ${{ secrets.TELE_CHATID }}
        TELE_TOKEN: ${{ secrets.TELE_TOKEN }}
      run: |
        if [ "${{ steps.compile.outputs.status }}" = "success" ]; then
            curl -X POST "https://api.telegram.org/bot$TELE_TOKEN/sendMessage" \
              -H "Content-Type: application/json" \
              -d "{\"chat_id\": \"$TELE_CHATID\", \"text\": \"固件编译成功\"}"
        else
            curl -X POST "https://api.telegram.org/bot$TELE_TOKEN/sendMessage" \
              -H "Content-Type: application/json" \
              -d "{\"chat_id\": \"$TELE_CHATID\", \"text\": \"固件编译失败\"}"
        fi

    - name: "Organize Files"
      if: steps.compile.outputs.status == 'success' && !cancelled()
      run: |
        mkdir -p openwrt/packages
        mkdir -p openwrt/firmware
        mv openwrt/bin/targets/*/*/packages/* openwrt/packages/
        rm -rf openwrt/bin/targets/*/*/packages
        mv openwrt/bin/targets/*/*/* openwrt/firmware/
        useVersionInfo=$(git show -s --date=short --format="提交人: %an<br/>提交时间: %cd<br/>提交内容: %s<br/>commit hash: %H")
        echo "useVersionInfo=$useVersionInfo" >> $GITHUB_ENV
        echo "DATE=$(date "+%Y%m%d%H%M")" >> $GITHUB_ENV

    - name: "Upload Packages to Action"
      uses: actions/upload-artifact@main
      if: steps.compile.outputs.status == 'success' && github.event.inputs.upload_packages == 'true' && !cancelled()
      with:
        name: OpenWrt_bin${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}
        path: openwrt/packages/

    - name: "Upload Firmware to Action"
      uses: actions/upload-artifact@v4.3.6
      if: steps.compile.outputs.status == 'success' && github.event.inputs.upload_action == 'true' && !cancelled()
      with:
        name: OpenWrt_firmware${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}
        path: openwrt/firmware/

    - name: "Upload Firmware to Releases"
      uses: ncipollo/release-action@main
      if: steps.compile.outputs.status == 'success' && github.event.inputs.upload_release == 'true' && !cancelled()
      with:
        name: ${{ env.DATE }} OpenWrt for ${{ env.FILE_NAME }}
        allowUpdates: true
        removeArtifacts: true
        tag: ${{ env.DATE }}_${{ env.FILE_NAME }}
        token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: openwrt/firmware/*
        body: |
          #### 源码最近提交信息:
          - ${{ env.useVersionInfo }}
          
    - name: "Delete Workflow Runs"
      uses: Mattraks/delete-workflow-runs@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        retain_days: 1
        keep_minimum_runs: 3
          
    - name: "Delete Releases"
      uses: ophub/delete-releases-workflows@main
      with:
        delete_releases: true
        releases_keep_latest: 3
        gh_token: ${{ secrets.GITHUB_TOKEN }}
